import { StyleSheet, Platform } from "react-native";
import { Colors } from "../../utils/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgDark,
  },
  backgroundImage: {
    opacity: 0.9,
  },
  backButton: {
    position: "absolute",
    left: 20,
    zIndex: 10,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(26,13,46,0.6)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.3)",
  },
  scrollContent: {
    alignItems: "center",
    paddingHorizontal: 24,
    paddingBottom: 60,
  },
  symbolWrapper: {
    marginBottom: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolOuterRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 2,
    borderColor: Colors.borderGoldMid,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolInnerRing: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: Colors.borderGoldStrong,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  symbolImage: {
    width: 80,
    height: 80,
  },
  nameText: {
    fontSize: 30,
    color: Colors.goldPale,
    marginBottom: 20,
    letterSpacing: 1.5,
  },
  pillsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 24,
  },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.borderGoldStrong,
    backgroundColor: "transparent",
  },
  pillIcon: {
    fontSize: 16,
    color: Colors.goldLight,
    marginRight: 6,
  },
  pillIconImage: {
    width: 20,
    height: 20,
    marginRight: 6,
  },
  pillText: {
    fontSize: 14,
    color: Colors.goldPale,
  },
  separator: {
    marginTop: 24,
    marginBottom: 20,
    width: "70%",
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(250, 218, 134, 0.5)",
  },
  unknownTimeWrapper: {
    width: "100%",
    marginBottom: 20,
    gap: 8,
  },
  unknownTimeBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  unknownTimeBannerTitle: {
    fontSize: 12,
    color: "rgba(212,175,55,0.6)",
    letterSpacing: 1,
    textTransform: "uppercase",
    fontWeight: "600",
  },
  unknownTimeBannerDesc: {
    fontSize: 12,
    color: "rgba(245,234,200,0.4)",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  lockedCardsRow: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
  },
  lockedCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.12)",
    backgroundColor: "rgba(26,13,46,0.5)",
    position: "relative",
  },
  lockIcon: {
    position: "absolute",
    top: 8,
    right: 8,
  },
  lockedCardLabel: {
    fontSize: 10,
    color: "rgba(212,175,55,0.3)",
    letterSpacing: 0.8,
    textAlign: "center",
    textTransform: "uppercase",
  },
  ctaButton: {
    width: "80%",
    height: 64,
    borderRadius: 32,
    borderWidth: 1.5,
    borderColor: Colors.borderGoldStrong,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 12,
  },
  ctaGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(205, 141, 255, 0.25)",
  },
  ctaText: {
    fontSize: 18,
    color: Colors.goldCream,
    letterSpacing: 1.5,
  },
  ctaSubText: {
    fontSize: 12,
    color: "rgba(245, 234, 200, 0.9)",
    marginTop: 4,
  },
  chartImage: {
    marginTop: 8,
    borderRadius: 999,
    overflow: "hidden",
    alignSelf: "center",
    borderWidth: 3,
    borderColor: Colors.borderGoldStrong,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: { elevation: 8 },
    }),
  },
  analysisWrapper: {
    width: "100%",
    marginTop: 36,
  },
  analysisTitleRow: {
    alignItems: "center",
    marginBottom: 16,
  },
  analysisTitle: {
    fontSize: 14,
    letterSpacing: 3,
    color: Colors.goldPrimary,
    textTransform: "uppercase",
    fontWeight: "400",
  },
  loadingCard: {
    borderWidth: 1,
    borderColor: "rgba(250, 218, 134, 0.2)",
    borderRadius: 16,
    backgroundColor: "rgba(26, 13, 46, 0.7)",
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    gap: 12,
  },
  loadingStars: {
    fontSize: 18,
    color: "rgba(250, 218, 134, 0.4)",
    letterSpacing: 8,
  },
  loadingPhrase: {
    fontSize: 15,
    color: Colors.goldPale,
    letterSpacing: 0.5,
    textAlign: "center",
    fontStyle: "italic",
  },
  loadingNote: {
    fontSize: 12,
    color: "rgba(245, 234, 200, 0.45)",
    letterSpacing: 0.5,
    marginTop: 4,
  },
  errorCard: {
    borderWidth: 1,
    borderColor: "rgba(255, 100, 100, 0.3)",
    borderRadius: 16,
    backgroundColor: "rgba(26, 13, 46, 0.7)",
    paddingVertical: 24,
    paddingHorizontal: 24,
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    fontSize: 14,
    color: "rgba(255, 180, 180, 0.9)",
    textAlign: "center",
  },
  retryText: {
    fontSize: 13,
    color: Colors.goldPrimary,
    letterSpacing: 0.5,
  },
  sectionsWrapper: {
    gap: 12,
  },
  chatButton: {
    marginTop: 16,
    alignSelf: "center",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(250, 218, 134, 0.35)",
    backgroundColor: "rgba(26, 13, 46, 0.5)",
  },
  chatButtonText: {
    fontSize: 13,
    color: Colors.goldPale,
    letterSpacing: 1.5,
  },
});
