import { StyleSheet, Platform } from "react-native";
import { ORBIT_SIZE, CENTER_SIZE, OUTER_ORBIT_SIZE, SCREEN_HEIGHT } from "./constants";
import { Colors } from "../../utils/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: SCREEN_HEIGHT * 0.05 + 50,
    overflow: "hidden",
  },
  title: {
    fontSize: 26,
    letterSpacing: 4,
    color: Colors.goldPale,
    marginBottom: 24,
    fontWeight: "400",
    textTransform: "uppercase",
  },
  orbitWrapper: {
    width: ORBIT_SIZE,
    height: ORBIT_SIZE,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  outerOrbit: {
    position: "absolute",
    width: OUTER_ORBIT_SIZE,
    height: OUTER_ORBIT_SIZE,
    borderRadius: OUTER_ORBIT_SIZE / 2,
    borderWidth: 1,
    borderColor: "rgba(250, 218, 134, 0.6)", // Colors.goldLight at 60%
    left: (ORBIT_SIZE - OUTER_ORBIT_SIZE) / 2,
    top: (ORBIT_SIZE - OUTER_ORBIT_SIZE) / 2,
  },
  innerOrbit: {
    position: "absolute",
    width: ORBIT_SIZE * 0.60,
    height: ORBIT_SIZE * 0.60,
    borderRadius: (ORBIT_SIZE * 0.60) / 2,
    borderWidth: 1,
    borderColor: Colors.goldLight,
  },
  /* ✨ CENTER GLOW SYSTEM */
  centerWrapper: {
    alignItems: "center",
    justifyContent: "center",
  },
  centerGlow: {
    position: "absolute",
    width: CENTER_SIZE * 1.15,
    height: CENTER_SIZE * 1.15,
    borderRadius: (CENTER_SIZE * 1.15) / 2,
    borderWidth: 0,
    borderColor: "rgba(250, 218, 134, 0.25)",
    shadowColor: "#FADA86",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 25,
    elevation: 25,
    top: -20,
  },
  centerCircle: {
    width: CENTER_SIZE,
    height: CENTER_SIZE,
    borderRadius: CENTER_SIZE / 2,
    borderWidth: 8,
    borderColor: Colors.goldLight,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  centerLabel: {
    color: Colors.goldPrimary,
    fontSize: 22,
    letterSpacing: 4,
    fontFamily: Platform.select({
      ios: "Georgia",
      android: "serif",
      default: "serif",
    }),
  },
  legend: {
    marginTop: 32,
    paddingHorizontal: 32,
  },
  legendTitle: {
    fontSize: 16,
    letterSpacing: 1.5,
    color: Colors.goldPale,
    marginBottom: 8,
  },
  legendText: {
    fontSize: 13,
    color: "rgba(245, 234, 200, 0.85)",
    textAlign: "center",
    lineHeight: 18,
  },
  emptyHint: {
    position: "absolute",
    bottom: SCREEN_HEIGHT * 0.2,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  emptyHintText: {
    fontSize: 14,
    color: "rgba(250, 218, 134, 0.8)",
    letterSpacing: 1,
  },
  pageDescription: {
    alignItems: "center",
    paddingHorizontal: 32,
    paddingTop: 16,
    paddingBottom: 4,
  },
  pageDescriptionTitle: {
    fontSize: 15,
    letterSpacing: 2.5,
    color: Colors.goldPrimary,
    fontWeight: "400",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  pageDescriptionText: {
    fontSize: 13,
    color: "rgba(245, 234, 200, 0.6)",
    textAlign: "center",
    lineHeight: 19,
  },
  pageDescriptionHint: {
    marginTop: 8,
    fontSize: 12,
    color: "rgba(250, 218, 134, 0.45)",
    letterSpacing: 1,
    fontStyle: "italic",
  },
  /* Step 2: self chart done, no one in orbit yet */
  addPromptCard: {
    position: "absolute",
    bottom: SCREEN_HEIGHT * 0.18,
    left: 24,
    right: 24,
    alignItems: "center",
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: "rgba(26, 13, 46, 0.88)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(250, 218, 134, 0.35)",
  },
  addPromptTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.goldLight,
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  addPromptText: {
    fontSize: 14,
    color: "rgba(247, 227, 165, 0.85)",
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 22,
    paddingHorizontal: 4,
  },
  addPromptButtonWrapper: {
    alignItems: "center",
    justifyContent: "center",
  },
  addPromptButtonGlow: {
    position: "absolute",
    top: -50,
    left: -40,
    right: -40,
    bottom: -8,
    borderRadius: 50,
    shadowColor: "#FADA86",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.95,
    shadowRadius: 32,
    elevation: 32,
  },
  addPromptButton: {
    backgroundColor: Colors.goldLight,
    paddingVertical: 13,
    paddingHorizontal: 36,
    borderRadius: 25,
    minWidth: 160,
    alignItems: "center",
  },
  addPromptButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.bgMain,
    letterSpacing: 1,
  },
});
